### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LilDDD** [Pabilo8/ImmersiveIntelligence#193]
A clear description of what the bug is.
Can't initialize minecraft with immersive intelligence present.

Initialize minecraft with immersiveintelligence-0.2.1.jar in the mods folder 

A clear description of what you expected to happen.
Initialize minecraft

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  wings (wings-1.1.6-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.4.1.jar)
  IILoadingPlugin (immersiveintelligence-core-0.2.1.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 6/11/22 5:58 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Immersive Intelligence (immersiveintelligence)
Caused by: java.lang.ExceptionInInitializerError
	at pl.pabilo8.immersiveintelligence.common.items.mechanical.ItemIIMotorBelt.<init>(ItemIIMotorBelt.java:40)
	at pl.pabilo8.immersiveintelligence.common.IIContent.<clinit>(IIContent.java:112)
	at pl.pabilo8.immersiveintelligence.common.CommonProxy.preInit(CommonProxy.java:621)
	at pl.pabilo8.immersiveintelligence.client.ClientProxy.preInit(ClientProxy.java:370)
	at pl.pabilo8.immersiveintelligence.ImmersiveIntelligence.preInit(ImmersiveIntelligence.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at pl.pabilo8.immersiveintelligence.common.items.mechanical.ItemIIMotorBelt$MotorBelt.<clinit>(ItemIIMotorBelt.java:91)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 306002352 bytes (291 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 35 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                           | Version              | Source                                        | Signature                                |
	|:----- |:---------------------------- |:-------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                    | 1.12.2               | minecraft.jar                                 | None                                     |
	| LCH   | mcp                          | 9.42                 | minecraft.jar                                 | None                                     |
	| LCH   | FML                          | 8.0.99.99            | forge-1.12.2-14.23.5.2859.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                        | 14.23.5.2859         | forge-1.12.2-14.23.5.2859.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | bspkrscore                   | 7.6.0.1              | [1.12]bspkrsCore-universal-7.6.0.1.jar        | None                                     |
	| LCH   | treecapitator                | 1.43.0               | [1.12]TreeCapitator-client-1.43.0.jar         | None                                     |
	| LCH   | aquaculture                  | 1.6.8                | Aquaculture-1.12.2-1.6.8.jar                  | None                                     |
	| LCH   | biomesoplenty                | 7.0.1.2445           | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar | None                                     |
	| LCH   | dungeonsmod                  | @VERSION@            | DungeonsMod-1.12.2-1.0.8.jar                  | None                                     |
	| LCH   | jei                          | 4.16.1.302           | jei_1.12.2-4.16.1.302.jar                     | None                                     |
	| LCH   | ebwizardry                   | 4.3.7                | ElectroblobsWizardry-4.3.7-MC1.12.2.jar       | None                                     |
	| LCH   | extrautils2                  | 1.0                  | extrautils2-1.12-1.9.9.jar                    | None                                     |
	| LCH   | hardcore_battle_towers_av_av | 2.0.1                | Hardcore+Battle+Towers+AV+2.0.1.jar           | None                                     |
	| LCH   | ichunutil                    | 7.2.2                | iChunUtil-1.12.2-7.2.2.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | immersiveengineering         | 0.12-98              | ImmersiveEngineering-0.12-98.jar              | None                                     |
	| LCH   | immersivepetroleum           | 1.1.10               | immersivepetroleum-1.12.2-1.1.10.jar          | None                                     |
	| LCH   | inventorypets                | 2.0.15               | inventorypets-1.12-2.0.15.jar                 | None                                     |
	| LCH   | inventorytweaks              | 1.64+dev.151.822d839 | InventoryTweaks-1.64+dev.151.jar              | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | journeymap                   | 1.12.2-5.7.1         | journeymap-1.12.2-5.7.1.jar                   | None                                     |
	| LCH   | medieval_craft               | 1.14.4               | MedievalCraft-1.12.2-1.18.0.jar               | None                                     |
	| LCH   | mekanism                     | 1.12.2-9.8.3.390     | Mekanism-1.12.2-9.8.3.390.jar                 | None                                     |
	| LCH   | morph                        | 7.2.0                | Morph-1.12.2-7.2.1.jar                        | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCH   | morpheus                     | 1.12.2-3.5.106       | Morpheus-1.12.2-3.5.106.jar                   | None                                     |
	| LCH   | llibrary                     | 1.7.20               | llibrary-1.7.20-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | mowziesmobs                  | 1.5.8                | mowziesmobs-1.5.8.jar                         | None                                     |
	| LCH   | naturescompass               | 1.8.5                | NaturesCompass-1.12.2-1.8.5.jar               | None                                     |
	| LCH   | roguelike                    | 2.4.1                | RoguelikeDungeonsFnarEdition-1.12.2-2.4.1.jar | None                                     |
	| LCH   | spartanweaponry              | 1.4.1                | SpartanWeaponry-1.12.2-1.4.1.jar              | None                                     |
	| LCH   | stg                          | 1.12.2-1.2.3         | stg-1.12.2-1.2.3.jar                          | None                                     |
	| LCH   | waystones                    | 4.1.0                | Waystones_1.12.2-4.1.0.jar                    | None                                     |
	| LCH   | wings                        | 1.1.6                | wings-1.1.6-1.12.2.jar                        | None                                     |
	| LCH   | mowzies_wings                | 1.0.0                | wings-1.1.6-1.12.2.jar                        | None                                     |
	| LCE   | immersiveintelligence        | 0.2.1                | immersiveintelligence-0.2.1.jar               | 770570c49a2652e64a9b29b9b9d9919ca68b7065 |
	| UD    | bauble_wings                 | 1.0.0                | wings-1.1.6-1.12.2.jar                        | None                                     |
	| UD    | mobends_wings                | 1.0.0                | wings-1.1.6-1.12.2.jar                        | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
  invtweaks.forge.asm.ContainerTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
wings (wings-1.1.6-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.4.1.jar)
  
IILoadingPlugin (immersiveintelligence-core-0.2.1.jar)
  pl.pabilo8.immersiveintelligence.common.asm.IIClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 457.51' Renderer: 'GeForce MX150/PCIe/SSE2'

**Environment**
 - OS: windows 10
 - Minecraft version: 12.2
 - Forge version: 14.24.5.2859
 - Immersive Intelligence version: 0.2.1
 - Immersive Engineering version: 0.12-98
If you have other mods installed, it would be nice if you send a list of them too (maybe it's not II's fault after all) ^^.
jei
biomes o'plenty
Roguelike Dungeons -- Fnar's Edition
aquaculture
waystones
journey map
mowzies mobs
llibrary
Spartan Weaponry
Treecapitator Updated
bspkrsCore Updated
revengeofthebatata.aternos.me
battle towers
morph 
jei_1.12.2-4.16.1.302
Biomes O' Plenty 1.12.2-7.0.1.2445
v2.4.1 Interim Development Patch
Aquaculture-1.12.2-1.6.8
Waystones_1.12.2-4.1.0
journeymap-1.12.2-5.7.1
Mowzie's Mobs - 1.5.8
LLibrary 1.7.20
SpartanWeaponry-1.12.2-1.4.1
[1.12]TreeCapitator-client-1.43.0
[1.12]bspkrsCore-universal-7.6.0.1
Hardcore Battle Towers AV
Morph-1.12.2-7.2.1
iChunUtil-1.12.2-7.2.2
nature's compass
Morpheus
Dungeons Mod
Extra Utilities
Inventory Tweaks [1.12 only]
Inventory Pets
Medieval Craft
SwingThroughGrass
ToroHealth Damage Indicators
Wings
Mekanism
Immersive Petrolleum.

My friends are also playing with the same modlist and do not have any problems initializing minecraft idk what to do thx. The only thing that is different in that they are playing on a pirated version of minecraft.

**Comment by LilDDD** [comment]
fixed, had to delete configs.
