### ISSUE TITLE
Modpack won´t start

### ISSUE THREAD

**Issue by Marci261001** [Pabilo8/ImmersiveIntelligence#205]
Hello I tried to include your addon but my modpack crashes before it can start i already did what you sugested but it still dont work
Heres the log

MultiMC version: 0.6.16-3431

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.66.119.38, 18.66.119.42, 18.66.119.35, 18.66.119.37]

session.minecraft.net resolves to:
    [52.7.214.17, 3.229.83.86, 52.45.69.223]

textures.minecraft.net resolves to:
    [99.86.4.114, 99.86.4.123, 99.86.4.29, 99.86.4.49]

api.mojang.com resolves to:
    [13.225.78.16, 13.225.78.6, 13.225.78.90, 13.225.78.43]

Minecraft folder is:
C:/backup/MultiMC/instances/1.12.27/.minecraft

Java path is:
C:/Program Files/Java/jre1.8.0_333/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_333, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/backup/MultiMC/instances/1.12.27/natives

Libraries:
  C:/backup/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/backup/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/backup/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/backup/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/backup/MultiMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/backup/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/backup/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/backup/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/backup/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/backup/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/backup/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/backup/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/backup/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/backup/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/backup/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/backup/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/backup/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/backup/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/backup/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/backup/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/backup/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/backup/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/backup/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/backup/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/backup/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/backup/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/backup/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/backup/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/backup/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/backup/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/backup/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/backup/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854-universal.jar
  C:/backup/MultiMC/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
  C:/backup/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/backup/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/backup/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/backup/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/backup/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/backup/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/backup/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  C:/backup/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  C:/backup/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/backup/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/backup/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/backup/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/backup/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/backup/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/backup/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/backup/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/backup/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/backup/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/backup/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/backup/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/backup/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [✔️] ImmersiveEngineering-0.12-89
  [✔️] immersiveintelligence-0.2.1

Params:
  --username  --version 1.12.2 --gameDir C:/backup/MultiMC/instances/1.12.27/.minecraft --assetsDir C:/backup/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx16327m, -Duser.language=en]

Minecraft process ID: 2476

Using onesix launcher.

[22:38:32] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[22:38:32] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[22:38:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[22:38:32] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[22:38:32] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_333, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_333
[22:38:32] [main/INFO] [FML]: Searching C:\backup\MultiMC\instances\1.12.27\.minecraft\mods for mods
[22:38:32] [main/WARN] [FML]: The coremod blusunrize.immersiveengineering.common.asm.IELoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:38:32] [main/WARN] [FML]: The coremod pl.pabilo8.immersiveintelligence.common.asm.IILoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[22:38:32] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:38:32] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[22:38:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:38:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:38:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:38:34] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[22:38:34] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[22:38:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:38:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[22:38:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:38:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:38:34] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[22:38:34] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[22:38:34] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[22:38:35] [Client thread/INFO] [minecraft/Minecraft]: Setting user: Marchy01
[22:38:38] [Client thread/INFO] [minecraft/Minecraft]: LWJGL Version: 2.9.4
[22:38:39] [Client thread/INFO] [FML]: Could not load splash.properties, will create a default one
[22:38:39] [Client thread/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_333, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1678766344 bytes (1600 MB) / 1822949376 bytes (1738 MB) up to 15219032064 bytes (14514 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx16327m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
IILoadingPlugin (immersiveintelligence-core-0.2.1.jar)
  pl.pabilo8.immersiveintelligence.common.asm.IIClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14761 Compatibility Profile Context 21.30.23.04 30.0.13023.4001' Renderer: 'Radeon RX 590 Series'
[22:38:39] [Client thread/INFO] [FML]: MinecraftForge v14.23.5.2854 Initialized
[22:38:39] [Client thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[22:38:39] [Client thread/INFO] [FML]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[22:38:39] [Client thread/INFO] [FML]: Replaced 1227 ore ingredients
[22:38:39] [Client thread/INFO] [FML]: Searching C:\backup\MultiMC\instances\1.12.27\.minecraft\mods for mods
[22:38:40] [Client thread/INFO] [FML]: Forge Mod Loader has identified 6 mods to load
[22:38:41] [Client thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, immersiveengineering, immersiveintelligence] at CLIENT
[22:38:41] [Client thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, immersiveengineering, immersiveintelligence] at SERVER
[22:38:41] [Thread-3/INFO] [FML]: Using sync timing. 200 frames of Display.update took 105181700 nanos
[22:38:42] [Client thread/ERROR] [FML]: An error occurred trying to load an EventBusSubscriber pl.pabilo8.immersiveintelligence.client.ClientProxy for modid immersiveintelligence
java.lang.NoClassDefFoundError: blusunrize/immersiveengineering/api/MultiblockHandler$MultiblockFormEvent$Post
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_333]
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_333]
	at java.lang.Class.privateGetPublicMethods(Unknown Source) ~[?:1.8.0_333]
	at java.lang.Class.privateGetPublicMethods(Unknown Source) ~[?:1.8.0_333]
	at java.lang.Class.getMethods(Unknown Source) ~[?:1.8.0_333]
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82) [AutomaticEventSubscriber.class:?]
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:612) [FMLModContainer.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_333]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_333]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_333]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_333]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_333]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_333]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_333]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_333]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_333]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_333]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_333]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_333]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_333]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_333]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_333]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_333]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: blusunrize.immersiveengineering.api.MultiblockHandler$MultiblockFormEvent$Post
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_333]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_333]
	... 52 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_333]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_333]
	... 52 more
[22:38:42] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  IILoadingPlugin (immersiveintelligence-core-0.2.1.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 7/25/22 10:38 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: blusunrize/immersiveengineering/api/MultiblockHandler$MultiblockFormEvent$Post
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:612)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoClassDefFoundError: blusunrize/immersiveengineering/api/MultiblockHandler$MultiblockFormEvent$Post
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetPublicMethods(Unknown Source)
	at java.lang.Class.privateGetPublicMethods(Unknown Source)
	at java.lang.Class.getMethods(Unknown Source)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 45 more
Caused by: java.lang.ClassNotFoundException: blusunrize.immersiveengineering.api.MultiblockHandler$MultiblockFormEvent$Post
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 52 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 54 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_333, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1268786824 bytes (1210 MB) / 2097152000 bytes (2000 MB) up to 15219032064 bytes (14514 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx16327m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version      | Source                                  | Signature                                |
	|:----- |:--------------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LC    | minecraft             | 1.12.2       | minecraft.jar                           | None                                     |
	| LC    | mcp                   | 9.42         | minecraft.jar                           | None                                     |
	| LC    | FML                   | 8.0.99.99    | forge-1.12.2-14.23.5.2854-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                 | 14.23.5.2854 | forge-1.12.2-14.23.5.2854-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | immersiveengineering  | 0.12-89      | ImmersiveEngineering-0.12-89.jar        | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LE    | immersiveintelligence | 0.2.1        | immersiveintelligence-0.2.1.jar         | 770570c49a2652e64a9b29b9b9d9919ca68b7065 |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
IILoadingPlugin (immersiveintelligence-core-0.2.1.jar)
  pl.pabilo8.immersiveintelligence.common.asm.IIClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14761 Compatibility Profile Context 21.30.23.04 30.0.13023.4001' Renderer: 'Radeon RX 590 Series'
[22:38:42] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\backup\MultiMC\instances\1.12.27\.minecraft\crash-reports\crash-2022-07-25_22.38.42-client.txt
Prozess endete mit dem Status -1 (0xffffffffffffffff).
Beachte, dass normalerweise weder der Exit-Code noch seine Beschreibung ausreichen, um Probleme zu diagnostizieren!
Lade immer den kompletten Log hoch und nicht nur den Exit-Code.
Clipboard copy at: 25 Jul 2022 22:39:21 +0200

**Comment by Pabilo8** [comment]
This is caused by using an old version of IE. Please update Immersive Engineering to [Version 0.12-98](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering/files/2974106).
