### ISSUE TITLE
[BUG] Crash during loading of version 0.2.1

### ISSUE THREAD

**Issue by Cthulhu-16** [Pabilo8/ImmersiveIntelligence#209]
**Describe the bug**
During the loading of minecraft the game crashes whilst attempting to load Immersive Intelligence version 0.2.1. At first, I had other mods installed too however I removed them, and the same issue occurred.

**To Reproduce**
1. Launch game (1.12.2-forge- 14.23.5.2855) with Immersive intelligence and immersive engineering (0.12-98)
2. wait while game loads
3. On step 2/7 during loading the game crashes

**Expected behavior**
Game loads and I play Minecraft

**Logs**
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  IILoadingPlugin (immersiveintelligence-core-0.2.1.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 8/7/22 12:45 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Immersive Intelligence (immersiveintelligence)
Caused by: java.lang.ExceptionInInitializerError
	at pl.pabilo8.immersiveintelligence.common.items.mechanical.ItemIIMotorBelt.<init>(ItemIIMotorBelt.java:40)
	at pl.pabilo8.immersiveintelligence.common.IIContent.<clinit>(IIContent.java:112)
	at pl.pabilo8.immersiveintelligence.common.CommonProxy.preInit(CommonProxy.java:621)
	at pl.pabilo8.immersiveintelligence.client.ClientProxy.preInit(ClientProxy.java:370)
	at pl.pabilo8.immersiveintelligence.ImmersiveIntelligence.preInit(ImmersiveIntelligence.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at pl.pabilo8.immersiveintelligence.common.items.mechanical.ItemIIMotorBelt$MotorBelt.<clinit>(ItemIIMotorBelt.java:91)
	... 46 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 234214072 bytes (223 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version      | Source                           | Signature                                |
	|:----- |:--------------------- |:------------ |:-------------------------------- |:---------------------------------------- |
	| LCH   | minecraft             | 1.12.2       | minecraft.jar                    | None                                     |
	| LCH   | mcp                   | 9.42         | minecraft.jar                    | None                                     |
	| LCH   | FML                   | 8.0.99.99    | forge-1.12.2-14.23.5.2855.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                 | 14.23.5.2855 | forge-1.12.2-14.23.5.2855.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | immersiveengineering  | 0.12-98      | ImmersiveEngineering-0.12-98.jar | None                                     |
	| LCE   | immersiveintelligence | 0.2.1        | immersiveintelligence-0.2.1.jar  | 770570c49a2652e64a9b29b9b9d9919ca68b7065 |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
IILoadingPlugin (immersiveintelligence-core-0.2.1.jar)
  pl.pabilo8.immersiveintelligence.common.asm.IIClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 30.0.100.9805' Renderer: 'Intel(R) UHD Graphics'
**Environment**
 - OS: Windows 10
 - Minecraft version: 1.12.2
 - Forge version:
 - Immersive Intelligence version: 0.2.1
 - Immersive Engineering version: 0.12-98

**Comment by Pabilo8** [comment]
This is a known issue caused by loading a pre-0.2.1 config file (motor belts had major changes). 
Please remove the II config file from `[main folder]/config/immersiveintelligence.cfg`. 
A new config file will be generated; if you made any changes to the old one, make sure to move them.

**Comment by Cthulhu-16** [comment]
Oh thank you so much
