### ISSUE TITLE
[BUG] Crash with HammerCore

### ISSUE THREAD

**Issue by Carvercarver1** [Pabilo8/ImmersiveIntelligence#35]
Chemical bath. As soon as liqud is inserted, it causes a crash.

Can be reproduced by installing HammerCore

Log by vanillafix:

> Description: Ticking block entity
> 
> java.lang.NullPointerException
>     at pl.pabilo8.immersiveintelligence.common.blocks.multiblocks.metal.tileentities.first.TileEntityChemicalBath.update(TileEntityChemicalBath.java:165)
>     at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38)
>     at net.minecraft.world.World.updateEntities(World.java:1835)
>     at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
>     at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
>     at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
>     at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
>     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
>     at java.lang.Thread.run(Unknown Source)

**Comment by Carvercarver1** [comment]
Update: for some reason it stopped crashing after a couple of times. Still required to test just in case

**Comment by Carvercarver1** [comment]
Testing with sulfuric acid.

Goes just with this: 
```
Ticking block entity

java.lang.NullPointerException
```

**Comment by Carvercarver1** [comment]
Seems to occur with printer too
Ticking block entity

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 33
    at java.lang.String.substring(Unknown Source)
    at pl.pabilo8.immersiveintelligence.common.blocks.multiblocks.metal.tileentities.first.TileEntityPrintingPress.onProcessFinishButInYellow(TileEntityPrintingPress.java:329)
    at pl.pabilo8.immersiveintelligence.common.blocks.multiblocks.metal.tileentities.first.TileEntityPrintingPress.update(TileEntityPrintingPress.java:211)
    at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38)
    at net.minecraft.world.World.updateEntities(World.java:1835)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
```
