### ISSUE TITLE
[BUG] Crash in  Atum

### ISSUE THREAD

**Issue by Carvercarver1** [Pabilo8/ImmersiveIntelligence#55]
Happens when firing howitzer in Atum for 1.12 during a sandstorm. Probably won't need a fix. 
Will be testing the other dimensions later.

```
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=type, clazz=class blusunrize.immersiveengineering.common.blocks.metal.BlockTypes_Connector, values=[CONNECTOR_LV, RELAY_LV, CONNECTOR_MV, RELAY_MV, CONNECTOR_HV, RELAY_HV, CONNECTOR_STRUCTURAL, TRANSFORMER, TRANSFORMER_HV, BREAKERSWITCH, REDSTONE_BREAKER, ENERGY_METER, CONNECTOR_REDSTONE, CONNECTOR_PROBE, FEEDTHROUGH]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:209)
    at blusunrize.immersiveengineering.common.blocks.metal.BlockConnector.isSideSolid(BlockConnector.java:119)
    at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.optifine.reflect.Reflector.callBoolean(Reflector.java:848)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.isSideSolid(BlockStateContainer.java:519)
    at com.teammetallurgy.atum.world.ChunkGeneratorAtum.canPlaceSandLayer(ChunkGeneratorAtum.java:382)
    at com.teammetallurgy.atum.world.WorldProviderAtum.canPlaceSandAt(WorldProviderAtum.java:148)
    at com.teammetallurgy.atum.world.WorldProviderAtum.updateWeather(WorldProviderAtum.java:219)
    at net.minecraft.world.World.updateWeather(World.java:2564)
    at net.minecraft.world.WorldServer.updateWeather(WorldServer.java:1236)
    at net.minecraft.world.World.tick(World.java:2541)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:179)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by Carvercarver1** [comment]
Related to Atum in general. Not only to II. Closing the issue, but I'll leave it here.
